### ISSUE TITLE
Merge with https://github.com/pfmonville/whole_history_rating ?

### ISSUE THREAD

**Issue by endolith** [wind23/whole_history_rating#1]
Both are python translations of the ruby code, and both are installable with pip.  It would be ideal if there were only one canonical implementation that everyone worked on together?  https://github.com/pfmonville/whole_history_rating has more stars than this repo. but otherwise I don't know if one is better than the other.

**Comment by wind23** [comment]
Thank you for your advice, and sorry for the delayed response. I have another application (https://github.com/wind23/whr_renju) that relies on this package. Therefore, I prefer not to merge these two repositories as it could potentially alter the behavior of certain code running in the product.

However, you are correct in noting the similarity between these two repositories. To differentiate them and improve the performance of my application, I have rewritten the core algorithm in C++. I have also provided Python interfaces that are connected to the C++ algorithm using Pybind11.

By adopting this approach, the package now runs significantly faster than the previous version, several times over. However, it is important to note that this may affect compatibility on different platforms. If you encounter any issues while using the package, please don't hesitate to contact me.

**Comment by endolith** [comment]
So now they have diverged, and one runs faster while the other has made improvements to the uncertainty, etc. https://github.com/pfmonville/whole_history_rating/releases  :/  I wish there were just one repo that contained the best of both, but it's your choice...

**Comment by wind23** [comment]
Well, if you have any idea about substantial feature updates, I'll be glad to consider to add them.

On the other hand, by replacing the entire programming language of the core algorithm, it means replacing more than 90% code of the whole project. It is not so easy to make such a pull request to merge it into another repository. Currently, the simplest solution is to continue maintaining a separate repository...
