### ISSUE TITLE
Is there any way to set initial rating?

### ISSUE THREAD

**Issue by astratsi** [wind23/whole_history_rating#6]
When I inserted first game results, initial highest ratings were 400~500. and after inserting 10 year results, highest rating is not over 1500.

Also there are many - rating players and there is also almost -1,000 rating player.

I would like to make overall ratings more higher, so is there any to set initial rating?

I used w2 parameter as 300.

**Comment by wind23** [comment]
This repo contains pure algorithms and does not consider the issue of initial ratings. However, it's important to note that the output of this algorithm may not be the final output you want to display; this work can be done at the output stage. For example, after obtaining the algorithm's output values, you can manually add 1500 points to each rating to achieve a more reasonable display rating.

**Comment by astratsi** [comment]
Thanks for thr explanation!

Did you apply the same method for renju as well?

**Comment by wind23** [comment]
> Thanks for thr explanation!
> 
> Did you apply the same method for renju as well?

Yes, in renju I use the value +1900

**Comment by astratsi** [comment]
thanks for the answer!

**Comment by astratsi** [comment]
Can I ask one more thing?
I wonder what w2 parameter value used in renju rating.

I'm not going to use exactly the same value, but I'd like to refer to the parameter direction!

**Comment by wind23** [comment]
> Can I ask one more thing? I wonder what w2 parameter value used in renju rating.
> 
> I'm not going to use exactly the same value, but I'd like to refer to the parameter direction!

After I tuned the parameters, I have used `w2 = 19.3` in renju rating.

In the paper of Rémi Coulom, he used `w2 = 14` in his go rating.

The default `w2 = 300` is a bit large in most cases, I suppose...

**Comment by astratsi** [comment]
Thanks!
